// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CollectBtn: typeof import('./src/components/translator/CollectBtn.vue')['default']
    ContentTrans: typeof import('./src/components/translator/ContentTrans.vue')['default']
    DictItems: typeof import('./src/components/translator/DictItems.vue')['default']
    Divider: typeof import('./src/components/translator/Divider.vue')['default']
    Editor: typeof import('./src/components/translator/Editor.vue')['default']
    Examples: typeof import('./src/components/translator/Examples.vue')['default']
    FindText: typeof import('./src/components/translator/FindText.vue')['default']
    IconBtn: typeof import('./src/components/base/IconBtn.vue')['default']
    LangController: typeof import('./src/components/translator/LangController.vue')['default']
    Loading: typeof import('./src/components/base/Loading.vue')['default']
    Options: typeof import('./src/components/translator/Options.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundBtn: typeof import('./src/components/translator/SoundBtn.vue')['default']
    SubTranslator: typeof import('./src/components/translator/SubTranslator.vue')['default']
    SubTransResult: typeof import('./src/components/translator/SubTransResult.vue')['default']
    SvgIcon: typeof import('./src/components/base/SvgIcon.vue')['default']
    ThemeElement: typeof import('./src/components/base/ThemeElement.vue')['default']
    TransDialog: typeof import('./src/components/translator/TransDialog.vue')['default']
    Translator: typeof import('./src/components/translator/Translator.vue')['default']
    TransResult: typeof import('./src/components/translator/TransResult.vue')['default']
    TransToast: typeof import('./src/components/translator/TransToast.vue')['default']
    TransTopBar: typeof import('./src/components/translator/TransTopBar.vue')['default']
  }
}
