// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CollectBtn: typeof import('./src/components/translator/CollectBtn.vue')['default']
    ContentTrans: typeof import('./src/components/translator/ContentTrans.vue')['default']
    DictItems: typeof import('./src/components/translator/DictItems.vue')['default']
    Divider: typeof import('./src/components/translator/Divider.vue')['default']
    Editor: typeof import('./src/components/translator/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Examples: typeof import('./src/components/translator/Examples.vue')['default']
    FindText: typeof import('./src/components/translator/FindText.vue')['default']
    IconBtn: typeof import('./src/components/base/IconBtn.vue')['default']
    LangController: typeof import('./src/components/translator/LangController.vue')['default']
    Loading: typeof import('./src/components/base/Loading.vue')['default']
    Options: typeof import('./src/components/translator/Options.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundBtn: typeof import('./src/components/translator/SoundBtn.vue')['default']
    SubTranslator: typeof import('./src/components/translator/SubTranslator.vue')['default']
    SubTransResult: typeof import('./src/components/translator/SubTransResult.vue')['default']
    SvgIcon: typeof import('./src/components/base/SvgIcon.vue')['default']
    TransDialog: typeof import('./src/components/translator/TransDialog.vue')['default']
    Translator: typeof import('./src/components/translator/Translator.vue')['default']
    TransResult: typeof import('./src/components/translator/TransResult.vue')['default']
    TransToast: typeof import('./src/components/translator/TransToast.vue')['default']
    TransTopBar: typeof import('./src/components/translator/TransTopBar.vue')['default']
  }
}
