export const engines:any = [
  {
    code: '__commonTrans__',
    engines: {
      bing: {
        code: 'bing__common'
      },
      google: {
        code: 'ggTrans__common'
      },
    }
  },
  {
    code: '__llm__',
    engines: {}
  }
]

export function getTransEngineIcon(engine:string) :string {
  switch (engine) {
    case 'ggTrans__common':
      return 'google_engine'
    case 'bing__common':
      return 'bing_engine'
    default:
      if (engine?.startsWith('llm__')) return 'icon-gengduo1'
      return 'icon-gengduo1'
  }
}


export const languages = {
    auto: { en: 'auto detect', 'zh-CN': '自动检测', ja: '自動検出'},
    __auto__: { en: 'auto exchange', 'zh-CN': '智能转换', ja: '自動変換'},
    en: { en: 'English', 'zh-CN': '英文', ja: '英語'},
    'zh-CN': { en: 'Chinese', 'zh-CN': '简体中文', ja: '中国語（簡体）'},
    ja: { en: 'Japanese', 'zh-CN': '日语', ja: '日本語'},
    ko: { en: 'Korean', 'zh-CN': '韩语', ja: '韓国語'},
    fr: { en: 'French', 'zh-CN': '法语', ja: 'フランス語'},
    de: { en: 'German', 'zh-CN': '德语', ja: 'ドイツ語'},
    es: { en: 'Spanish', 'zh-CN': '西班牙语', ja: 'スペイン語'},
    ru: { en: 'Russian', 'zh-CN': '俄语', ja: 'ロシア語'},
    'zh-TW': { en: 'Chinese(TW)', 'zh-CN': '繁体中文', ja: '中国語（繁体）'},
    th: { en: 'Thai', 'zh-CN': '泰语', ja: 'タイ語'},
    af: { en: 'Afrikaans', 'zh-CN': '南非荷兰语', ja: 'アフリカーンス語'},
    am: { en: 'Amharic', 'zh-CN': '阿姆哈拉语', ja: 'アムハラ語'},
    ar: { en: 'Arabic', 'zh-CN': '阿拉伯语', ja: 'アラビア語'},
    az: { en: 'Azerbaijani', 'zh-CN': '阿塞拜疆语', ja: 'アゼルバイジャン語'},
    be: { en: 'Belarusian', 'zh-CN': '白俄罗斯语', ja: 'ベラルーシ語'},
    bg: { en: 'Bulgarian', 'zh-CN': '保加利亚语', ja: 'ブルガリア語'},
    bn: { en: 'Bengali', 'zh-CN': '孟加拉语', ja: 'ベンガル語'},
    bs: { en: 'Bosnian', 'zh-CN': '波斯尼亚语', ja: 'ボスニア語'},
    ca: { en: 'Catalan', 'zh-CN': '加泰罗尼亚语', ja: 'カタルーニャ語'},
    ceb: { en: 'Cebuano', 'zh-CN': '宿务语', ja: 'セブアノ語'},
    co: { en: 'Corsican', 'zh-CN': '科西嘉语', ja: 'コルシカ語'},
    cs: { en: 'Czech', 'zh-CN': '捷克语', ja: 'チェコ語'},
    cy: { en: 'Welsh', 'zh-CN': '威尔士语', ja: 'ウェールズ語'},
    da: { en: 'Danish', 'zh-CN': '丹麦语', ja: 'デンマーク語'},
    el: { en: 'Greek', 'zh-CN': '希腊语', ja: 'ギリシャ語'},
    eo: { en: 'Esperanto', 'zh-CN': '世界语', ja: 'エスペラント語'},
    et: { en: 'Estonian', 'zh-CN': '爱沙尼亚语', ja: 'エストニア語'},
    eu: { en: 'Basque', 'zh-CN': '巴斯克语', ja: 'バスク語'},
    fa: { en: 'Persian', 'zh-CN': '波斯语', ja: 'ペルシア語'},
    fi: { en: 'Finnish', 'zh-CN': '芬兰', ja: 'フィンランド語'},
    fy: { en: 'Frisian', 'zh-CN': '弗里西亚语', ja: 'フリジア語'},
    ga: { en: 'Irish', 'zh-CN': '爱尔兰语', ja: 'アイルランド語'},
    gd: { en: 'Scots Gaelic', 'zh-CN': '苏格兰语', ja: 'スコットランド・ゲール語'},
    gl: { en: 'Galician', 'zh-CN': '加利西亚语', ja: 'ガリシア語'},
    gu: { en: 'Gujarati', 'zh-CN': '古吉拉特语', ja: 'グジャラート語'},
    ha: { en: 'Hausa', 'zh-CN': 'Hausa.', ja: 'ハウサ語'},
    haw: { en: 'Hawaiian', 'zh-CN': '夏威夷语', ja: 'ハワイ語'},
    he: { en: 'Hebrew', 'zh-CN': '希伯来语', ja: 'ヘブライ語'},
    hi: { en: 'Hindi', 'zh-CN': '印地语', ja: 'ヒンディー語'},
    hmn: { en: 'Hmong', 'zh-CN': '苗语', ja: 'モン語'},
    hr: { en: 'Croatian', 'zh-CN': '克罗地亚语', ja: 'クロアチア語'},
    ht: { en: 'Haitian', 'zh-CN': '海地语', ja: 'ハイチ語'},
    hu: { en: 'Hungarian', 'zh-CN': '匈牙利语', ja: 'ハンガリー語'},
    hy: { en: 'Armenian', 'zh-CN': '亚美尼亚语', ja: 'アルメニア語'},
    id: { en: 'Indonesian', 'zh-CN': '印尼语', ja: 'インドネシア語'},
    is: { en: 'Icelandic', 'zh-CN': '冰岛语', ja: 'アイスランド語'},
    it: { en: 'Italian', 'zh-CN': '意大利语', ja: 'イタリア語'},
    iw: { en: 'Hebrew', 'zh-CN': '希伯来语', ja: 'ヘブライ語'},
    jw: { en: 'Javanese', 'zh-CN': '爪哇语', ja: 'ジャワ語'},
    ka: { en: 'Georgian', 'zh-CN': '格鲁吉亚语', ja: 'グルジア語'},
    kk: { en: 'Kazakh', 'zh-CN': '哈萨克', ja: 'カザフ語'},
    km: { en: 'Khmer', 'zh-CN': '高棉', ja: 'クメール語'},
    kn: { en: 'Kannada', 'zh-CN': '凯纳达', ja: 'カンナダ語'},
    ku: {en: 'Kurdish','zh-CN': '库尔德', ja: 'クルド語'},
    ky: { en: 'Kyrgyz', 'zh-CN': '吉尔吉斯语', ja: 'キルギス語'},
    la: { en: 'Latin', 'zh-CN': '拉丁语', ja: 'ラテン語'},
    lb: { en: 'Luxembourgish', 'zh-CN': '卢森堡语', ja: 'ルクセンブルク語'},
    lo: { en: 'Lao', 'zh-CN': '老挝', ja: 'ラオ語'},
    lt: { en: 'Lithuanian', 'zh-CN': '立陶宛语', ja: 'リトアニア語'},
    lv: { en: 'Latvian', 'zh-CN': '拉脱维亚语', ja: 'ラトビア語'},
    mg: { en: 'Malagasy', 'zh-CN': '马尔加什', ja: 'マダガスカル語'},
    mi: { en: 'Maori', 'zh-CN': '毛利语', ja: 'マオリ語'},
    mk: { en: 'Macedonian', 'zh-CN': '马其顿语', ja: 'マケドニア語'},
    ml: { en: 'Malayalam', 'zh-CN': '马拉雅拉姆', ja: 'マラヤーラム語'},
    mn: { en: 'Mongolian', 'zh-CN': '蒙古语', ja: 'モンゴル語'},
    mr: { en: 'Marathi', 'zh-CN': '马拉地语', ja: 'マラーティー語'},
    ms: { en: 'Malay', 'zh-CN': '马来语', ja: 'マレー語'},
    mt: { en: 'Maltese', 'zh-CN': '马耳他语', ja: 'マルタ語'},
    my: { en: 'Myanmar', 'zh-CN': '缅甸语', ja: 'ミャンマー語'},
    ne: { en: 'Nepali', 'zh-CN': '尼泊尔语', ja: 'ネパール語'},
    nl: { en: 'Dutch', 'zh-CN': '荷兰语', ja: 'オランダ語'},
    no: { en: 'Norwegian', 'zh-CN': '挪威语', ja: 'ノルウェー語'},
    ny: { en: 'Chichewa', 'zh-CN': 'Chichewa.', ja: 'チェワ語'},
    pa: { en: 'Punjabi', 'zh-CN': '旁遮普语', ja: 'パンジャブ語'},
    pl: { en: 'Polish', 'zh-CN': '波兰语', ja: 'ポーランド語'},
    ps: { en: 'Pashto', 'zh-CN': '普什图语', ja: 'パシュトー語'},
    pt: { en: 'Portuguese', 'zh-CN': '葡萄牙语', ja: 'ポルトガル語'},
    ro: { en: 'Romanian', 'zh-CN': '罗马尼亚语', ja: 'ルーマニア語'},
    sd: { en: 'Sindhi', 'zh-CN': '信德语', ja: 'シンド語'},
    si: { en: 'Sinhala', 'zh-CN': '僧伽罗语', ja: 'シンハラ語'},
    sk: { en: 'Slovak', 'zh-CN': '斯洛伐克语', ja: 'スロバキア語'},
    sl: { en: 'Slovenian', 'zh-CN': '斯洛文尼亚语', ja: 'スロベニア語'},
    sm: { en: 'Samoan', 'zh-CN': '萨摩亚语', ja: 'サモア語'},
    sn: { en: 'Shona', 'zh-CN': 'Shona', ja: 'ショナ語'},
    so: { en: 'Somali', 'zh-CN': '索马里语', ja: 'ソマリ語'},
    sq: { en: 'Albanian', 'zh-CN': '阿尔巴尼亚语', ja: 'アルバニア語'},
    sr: { en: 'Serbian', 'zh-CN': '塞尔维亚语', ja: 'セルビア語'},
    st: { en: 'Sesotho', 'zh-CN': '索托托', ja: 'ソト語'},
    su: { en: 'Sundanese', 'zh-CN': '巽他语', ja: 'スンダ語'},
    sv: { en: 'Swedish', 'zh-CN': '瑞典语', ja: 'スウェーデン語'},
    sw: { en: 'Swahili', 'zh-CN': '斯瓦希里语', ja: 'スワヒリ語'},
    ta: { en: 'Tamil', 'zh-CN': '泰米尔', ja: 'タミル語'},
    te: { en: 'Telugu', 'zh-CN': '泰卢固语', ja: 'テルグ語'},
    tg: { en: 'Tajik', 'zh-CN': '塔吉克语', ja: 'タジク語'},
    tl: { en: 'Filipino', 'zh-CN': '菲律宾语', ja: 'フィリピノ語'},
    tr: { en: 'Turkish', 'zh-CN': '土耳其语', ja: 'トルコ語'},
    uk: { en: 'Ukrainian', 'zh-CN': '乌克兰语', ja: 'ウクライナ語'},
    ur: { en: 'Urdu', 'zh-CN': '乌尔都语', ja: 'ウルドゥー語'},
    uz: { en: 'Uzbek', 'zh-CN': '乌兹别克语', ja: 'ウズベク語'},
    vi: { en: 'Vietnamese', 'zh-CN': '越南语', ja: 'ベトナム語'},
    xh: { en: 'Xhosa', 'zh-CN': '科萨', ja: 'コサ語'},
    yi: { en: 'Yiddish', 'zh-CN': '意第绪语', ja: 'イディッシュ語'},
    yo: { en: 'Yoruba', 'zh-CN': '约鲁巴语', ja: 'ヨルバ語'},
    zu: { en: 'Zulu', 'zh-CN': '祖鲁', ja: 'ズールー語'}
}



export const SToBaidu:Iterable<readonly [string, string]> = [
  [ 'auto', 'auto' ], [ 'zh-CN', 'zh' ], [ 'zh-TW', 'cht' ], [ 'af', 'afr' ],
  [ 'am', 'amh' ],    [ 'ar', 'ara' ],   [ 'az', 'aze' ],    [ 'be', 'bel' ],
  [ 'bg', 'bul' ],    [ 'bn', 'ben' ],   [ 'bs', 'bos' ],    [ 'ca', 'cat' ],
  [ 'ceb', 'ceb' ],   [ 'co', 'cos' ],   [ 'cs', 'cs' ],     [ 'cy', 'wel' ],
  [ 'da', 'dan' ],    [ 'de', 'de' ],    [ 'el', 'el' ],     [ 'en', 'en' ],
  [ 'eo', 'epo' ],    [ 'es', 'spa' ],   [ 'et', 'est' ],    [ 'eu', 'baq' ],
  [ 'fa', 'per' ],    [ 'fi', 'fin' ],   [ 'fr', 'fra' ],    [ 'ga', 'gle' ],
  [ 'gd', 'gla' ],    [ 'gl', 'glg' ],   [ 'gu', 'guj' ],    [ 'ha', 'hau' ],
  [ 'haw', 'haw' ],   [ 'he', 'heb' ],   [ 'hi', 'hi' ],     [ 'hmn', 'hmn' ],
  [ 'hr', 'hrv' ],    [ 'ht', 'ht' ],    [ 'hu', 'hu' ],     [ 'hy', 'arm' ],
  [ 'id', 'id' ],     [ 'ig', 'ibo' ],   [ 'is', 'ice' ],    [ 'it', 'it' ],
  [ 'iw', 'heb' ],    [ 'ja', 'jp' ],    [ 'jw', 'jav' ],    [ 'ka', 'geo' ],
  [ 'km', 'hkm' ],    [ 'ko', 'kor' ],   [ 'ku', 'kur' ],    [ 'ky', 'kir' ],
  [ 'la', 'lat' ],    [ 'lb', 'ltz' ],   [ 'lo', 'lao' ],    [ 'lt', 'lit' ],
  [ 'lv', 'lav' ],    [ 'mi', 'mao' ],   [ 'mk', 'mac' ],    [ 'ml', 'mal' ],
  [ 'mr', 'mar' ],    [ 'ms', 'may' ],   [ 'mt', 'mlt' ],    [ 'my', 'bur' ],
  [ 'ne', 'nep' ],    [ 'nl', 'nl' ],    [ 'no', 'nor' ],    [ 'pa', 'pan' ],
  [ 'pl', 'pl' ],     [ 'ps', 'pus' ],   [ 'pt', 'pt' ],     [ 'ro', 'rom' ],
  [ 'ru', 'ru' ],     [ 'sd', 'snd' ],   [ 'si', 'sin' ],    [ 'sk', 'sk' ],
  [ 'sl', 'slo' ],    [ 'sm', 'sm' ],    [ 'so', 'som' ],    [ 'sq', 'alb' ],
  [ 'sr', 'srp' ],    [ 'su', 'sun' ],   [ 'sv', 'swe' ],    [ 'sw', 'swa' ],
  [ 'ta', 'tam' ],    [ 'te', 'tel' ],   [ 'tg', 'tgk' ],    [ 'th', 'th' ],
  [ 'tl', 'fil' ],    [ 'tr', 'tr' ],    [ 'uk', 'ukr' ],    [ 'ur', 'urd' ],
  [ 'vi', 'vie' ],    [ 'xh', 'xho' ],   [ 'yi', 'yid' ],    [ 'yo', 'yor' ],
  [ 'zu', 'zul' ],
]

export const SToGoogle: Iterable<readonly [string, string]> = [
  [ 'auto', 'auto' ], [ 'zh-CN', 'zh-CN' ], [ 'zh-TW', 'zh-TW' ],
      [ 'af', 'af' ],     [ 'am', 'am' ],       [ 'ar', 'ar' ],
      [ 'az', 'az' ],     [ 'be', 'be' ],       [ 'bg', 'bg' ],
      [ 'bn', 'bn' ],     [ 'bs', 'bs' ],       [ 'ca', 'ca' ],
      [ 'ceb', 'ceb' ],   [ 'co', 'co' ],       [ 'cs', 'cs' ],
      [ 'cy', 'cy' ],     [ 'da', 'da' ],       [ 'de', 'de' ],
      [ 'el', 'el' ],     [ 'en', 'en' ],       [ 'eo', 'eo' ],
      [ 'es', 'es' ],     [ 'et', 'et' ],       [ 'eu', 'eu' ],
      [ 'fa', 'fa' ],     [ 'fi', 'fi' ],       [ 'fr', 'fr' ],
      [ 'fy', 'fy' ],     [ 'ga', 'ga' ],       [ 'gd', 'gd' ],
      [ 'gl', 'gl' ],     [ 'gu', 'gu' ],       [ 'ha', 'ha' ],
      [ 'haw', 'haw' ],   [ 'he', 'he' ],       [ 'hi', 'hi' ],
      [ 'hmn', 'hmn' ],   [ 'hr', 'hr' ],       [ 'ht', 'ht' ],
      [ 'hu', 'hu' ],     [ 'hy', 'hy' ],       [ 'id', 'id' ],
      [ 'ig', 'ig' ],     [ 'is', 'is' ],       [ 'it', 'it' ],
      [ 'iw', 'iw' ],     [ 'ja', 'ja' ],       [ 'jw', 'jw' ],
      [ 'ka', 'ka' ],     [ 'kk', 'kk' ],       [ 'km', 'km' ],
      [ 'kn', 'kn' ],     [ 'ko', 'ko' ],       [ 'ku', 'ku' ],
      [ 'ky', 'ky' ],     [ 'la', 'la' ],       [ 'lb', 'lb' ],
      [ 'lo', 'lo' ],     [ 'lt', 'lt' ],       [ 'lv', 'lv' ],
      [ 'mg', 'mg' ],
      [ 'mi', 'mi' ], [ 'mk', 'mk' ], [ 'ml', 'ml' ],
      [ 'mn', 'mn' ], [ 'mr', 'mr' ], [ 'ms', 'ms' ],
      [ 'mt', 'mt' ], [ 'my', 'my' ], [ 'ne', 'ne' ],
      [ 'nl', 'nl' ], [ 'no', 'no' ], [ 'ny', 'ny' ],
      [ 'pa', 'pa' ], [ 'pl', 'pl' ], [ 'ps', 'ps' ],
      [ 'pt', 'pt' ], [ 'ro', 'ro' ], [ 'ru', 'ru' ],
      [ 'sd', 'sd' ], [ 'si', 'si' ], [ 'sk', 'sk' ],
      [ 'sl', 'sl' ], [ 'sm', 'sm' ], [ 'sn', 'sn' ],
      [ 'so', 'so' ], [ 'sq', 'sq' ], [ 'sr', 'sr' ],
      [ 'st', 'st' ], [ 'su', 'su' ], [ 'sv', 'sv' ],
      [ 'sw', 'sw' ], [ 'ta', 'ta' ], [ 'te', 'te' ],
      [ 'tg', 'tg' ], [ 'th', 'th' ], [ 'tl', 'tl' ],
      [ 'tr', 'tr' ], [ 'uk', 'uk' ], [ 'ur', 'ur' ],
      [ 'uz', 'uz' ], [ 'vi', 'vi' ], [ 'xh', 'xh' ],
      [ 'yi', 'yi' ], [ 'yo', 'yo' ], [ 'zu', 'zu' ]
]

export const LangSysToBing:Iterable<readonly [string, string]> = [
  ["auto", "auto-detect"],
  ["ar", "ar"],
  ["ga", "ga"],
  ["et", "et"],
  ["or", "or"],
  ["bg", "bg"],
  ["is", "is"],
  ["pl", "pl"],
  ["bs", "bs-Latn"],
  ["fa", "fa"],
  ["prs", "prs"],
  ["da", "da"],
  ["de", "de"],
  ["ru", "ru"],
  ["fr", "fr"],
  ["zh-TW", "zh-Hant"],
  ["fil", "fil"],
  ["fj", "fj"],
  ["fi", "fi"],
  ["gu", "gu"],
  ["kk", "kk"],
  ["ht", "ht"],
  ["ko", "ko"],
  ["nl", "nl"],
  ["ca", "ca"],
  ["zh-CN", "zh-Hans"],
  ["cs", "cs"],
  ["kn", "kn"],
  ["otq", "otq"],
  ["tlh", "tlh"],
  ["hr", "hr"],
  ["lv", "lv"],
  ["lt", "lt"],
  ["ro", "ro"],
  ["mg", "mg"],
  ["mt", "mt"],
  ["mr", "mr"],
  ["ml", "ml"],
  ["ms", "ms"],
  ["mi", "mi"],
  ["bn", "bn-BD"],
  ["hmn", "mww"],
  ["af", "af"],
  ["pa", "pa"],
  ["pt", "pt"],
  ["ps", "ps"],
  ["ja", "ja"],
  ["sv", "sv"],
  ["sm", "sm"],
  ["sr-Latn", "sr-Latn"],
  ["sr-Cyrl", "sr-Cyrl"],
  ["no", "nb"],
  ["sk", "sk"],
  ["sl", "sl"],
  ["sw", "sw"],
  ["ty", "ty"],
  ["te", "te"],
  ["ta", "ta"],
  ["th", "th"],
  ["to", "to"],
  ["tr", "tr"],
  ["cy", "cy"],
  ["ur", "ur"],
  ["uk", "uk"],
  ["es", "es"],
  ["he", "iw"],
  ["el", "el"],
  ["hu", "hu"],
  ["it", "it"],
  ["hi", "hi"],
  ["id", "id"],
  ["en", "en"],
  ["yua", "yua"],
  ["yue", "yua"],
  ["vi", "vi"],
  ["ku", "ku"],
  ["kmr", "kmr"],
]

